spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_flyway?currentSchema=app-db
    username: haritha
    password: haritha
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration/postgresql



